### ISSUE TITLE
I have imported jpbc, but the following problem occurs

### ISSUE THREAD

**Issue by Lvyingnan1002** [junwei-wang/cpabe#11]
//start to setup
java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': ???????¨
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:375)
	at com.sun.jna.Native.loadLibrary(Native.java:360)
	at it.unisa.dia.gas.plaf.jpbc.wrapper.jna.WrapperLibraryProvider.<clinit>(WrapperLibraryProvider.java:14)
	at it.unisa.dia.gas.plaf.jpbc.pbc.PairingFactory.isPBCAvailable(PairingFactory.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<init>(PairingFactory.java:49)
	at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<clinit>(PairingFactory.java:20)
	at bswabe.Bswabe.setup(Bswabe.java:38)
	at cpabe.Cpabe.setup(Cpabe.java:30)
	at DemoForCpabe.main(DemoForCpabe.java:419)
Exception in thread "main" java.io.FileNotFoundException: file_dir\pub_key (系统找不到指定的路径。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at cpabe.Common.spitFile(Common.java:25)
	at cpabe.Cpabe.setup(Cpabe.java:34)
	at DemoForCpabe.main(DemoForCpabe.java:419)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.jna.Native (file:/F:/PROJECT/CPABE/jpbc/jars/jna-3.2.5.jar) to field java.lang.ClassLoader.nativeLibraries
WARNING: Please consider reporting this to the maintainers of com.sun.jna.Native
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by junwei-wang** [comment]
Duplicate closed issue #6 .
