### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The specified module could not be found. ERROR

### ISSUE THREAD

**Issue by Architha18** [junwei-wang/cpabe#6]
SHOWS "java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The specified module could not be found" ERROR AFTER RUNNING.

**Comment by junwei-wang** [comment]
Please use jpbc library

**Comment by jojo9656** [comment]
I'm using jpbc library but also it shows this error

java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The specified module could not be found.

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:375)
	at com.sun.jna.Native.loadLibrary(Native.java:360)
	at it.unisa.dia.gas.plaf.jpbc.wrapper.jna.WrapperLibraryProvider.<clinit>(WrapperLibraryProvider.java:14)
	at it.unisa.dia.gas.plaf.jpbc.pbc.PairingFactory.isPBCAvailable(PairingFactory.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<init>(PairingFactory.java:59)
	at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<clinit>(PairingFactory.java:21)
	at bswabe.Bswabe.setup(Bswabe.java:38)
	at cpabe.Cpabe.setup(Cpabe.java:29)
	at java_2_cpabe.DemoForCpabe.main(DemoForCpabe.java:421)

**Comment by junwei-wang** [comment]
I have moved the project to build by Maven.
The dependency problem will be automatically solved.
Checkout BUILD.md

**Comment by junwei-wang** [comment]
Duplicate issue #8
