### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The specified module could not be found.

### ISSUE THREAD

**Issue by jojo9656** [junwei-wang/cpabe#8]
I'm using jpbc library but also it shows this error

java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The specified module could not be found.

at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
at com.sun.jna.Library$Handler.<init>(Library.java:140)
at com.sun.jna.Native.loadLibrary(Native.java:375)
at com.sun.jna.Native.loadLibrary(Native.java:360)
at it.unisa.dia.gas.plaf.jpbc.wrapper.jna.WrapperLibraryProvider.<clinit>(WrapperLibraryProvider.java:14)
at it.unisa.dia.gas.plaf.jpbc.pbc.PairingFactory.isPBCAvailable(PairingFactory.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<init>(PairingFactory.java:59)
at it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<clinit>(PairingFactory.java:21)
at bswabe.Bswabe.setup(Bswabe.java:38)
at cpabe.Cpabe.setup(Cpabe.java:29)
at java_2_cpabe.DemoForCpabe.main(DemoForCpabe.java:421)

**Comment by yxkyong** [comment]
Excuse me , I met the same problem. Have you solved the  problem?

**Comment by jojo9656** [comment]
Yup

**Comment by junwei-wang** [comment]
Please send your pull request to fix the bug

**Comment by yxkyong** [comment]
Could you please tell me how to solve it ?  I tried, but I couldn't  find a solution.

**Comment by jojo9656** [comment]
It's the problem with the jar file imported

**Comment by yxkyong** [comment]
I have imported the required jar (jPBC 1.2.0), and my operating system is mac OS , Could you please show me more details?

**Comment by jojo9656** [comment]
OK
I will send the code itself

**Comment by jojo9656** [comment]
You have to run java\algorithm\DemoForCpabe.java
​
 java.rar
<https://drive.google.com/file/d/1Mn84XIDiELphW0UypZQ77mtU_kHz38UR/view?usp=drive_web>
​
and also include this libraries

​
For any queries contact

**Comment by junwei-wang** [comment]
@jojo9656 Could you please send a pull request for you updating?

**Comment by Lvyingnan1002** [comment]
我也是遇到了同样的问题，请问能详细说明下解决的过程么？非常感谢

**Comment by junwei-wang** [comment]
Duplicate issue #8.

**Comment by knagaraju799** [comment]
I am getting  Unable to load library 'jpbc-pbc': The specified module could not be found. ... please help me how to solve it . junwei-wang

**Comment by junwei-wang** [comment]
The reason is that java could not locate where is the jpbc-pbc jars. You can put all the related jars in your running path for java.

For more information, could you explain you building platform and building process.
I experiment on MacOS, there is no such error report.

**Comment by knagaraju799** [comment]
Thank you for your reply .

I am using windows 8.5 Netbeans IDE in that I have uploaded all jar files
which are related to JPBC . but I am getting  this Error.. Please help e to
solve .




java.lang.UnsatisfiedLinkError: Unable to load library 'jpbc-pbc': The
specified module could not be found.

at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
at com.sun.jna.Library$Handler.<init>(Library.java:140)
at com.sun.jna.Native.loadLibrary(Native.java:375)
at com.sun.jna.Native.loadLibrary(Native.java:360)
at
it.unisa.dia.gas.plaf.jpbc.wrapper.jna.WrapperLibraryProvider.<clinit>(WrapperLibraryProvider.java:14)
at
it.unisa.dia.gas.plaf.jpbc.pbc.PairingFactory.isPBCAvailable(PairingFactory.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<init>(PairingFactory.java:49)
at
it.unisa.dia.gas.plaf.jpbc.pairing.PairingFactory.<clinit>(PairingFactory.java:20)
at ALGOS.setup(ALGOS.java:43)
at AA.setup(AA.java:25)
at ABE_ALGO.main(ABE_ALGO.java:34)

**Comment by lstrgar** [comment]
I'm having the same issue working with jpbc version 1.2.1. jojo9656 can you elaborate on the fix? I've included what I believe are all the jpbc jar files. I'm running high sierra version 10.13.6. Classpath is definitely set properly. Very stuck here.
